import type { Metadata } from "next";
import "./globals.css";
import RootProvider from "./providers";
import RoutingNavbar from "@/components/Routes/RoutingNavbar";
import fonts from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${fonts.poppins.className}`}
    >
      <head />
      <body>
        <RoutingNavbar />
        {children}
      </body>
    </html>
  );
}
